version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      # [skip ci] dimasukkan ke dalam prefix agar valid dengan skema Dependabot v2
      prefix: 'chore(deps) [skip ci]'
