export default defineAppConfig({
  ui: {
    colors: {
      primary: 'permadi',
      neutral: 'permadi',
    },
    card: {
      slots: {
        root: 'rounded-md ring ring-permadi-900 dark:ring-permadi-700 overflow-hidden',
        header: 'p-2 sm:px-2',
        body: 'p-2 sm:p-2',
        footer: 'p-2 sm:px-2',
      },
      variants: {
        variant: {
          solid: {
            root: 'bg-inverted text-inverted',
          },
          outline: {
            root: 'bg-default ring ring-default divide-y divide-default',
          },
          soft: {
            root: 'bg-elevated/50 divide-y divide-default',
          },
          subtle: {
            root: 'bg-elevated/50 ring ring-default divide-y divide-default',
          },
        },
      },
      defaultVariants: {
        variant: 'outline',
      },
    },
    icons: {
      arrowDown: 'i-narr-arrow-down',
      arrowLeft: 'i-narr-arrow-left',
      arrowRight: 'i-narr-arrow-right',
      arrowUp: 'i-narr-arrow-up',
      caution: 'i-narr-caution',
      check: 'i-narr-check',
      chevronDoubleLeft: 'i-narr-chevron-double-left',
      chevronDoubleRight: 'i-narr-chevron-double-right',
      chevronDown: 'i-narr-chevron-down',
      chevronLeft: 'i-narr-chevron-left',
      chevronRight: 'i-narr-chevron-right',
      chevronUp: 'i-narr-chevron-up',
      close: 'i-narr-close',
      copy: 'i-narr-copy',
      copyCheck: 'i-narr-copy-check',
      dark: 'i-narr-dark',
      drag: 'i-narr-drag',
      ellipsis: 'i-narr-ellipsis',
      error: 'i-narr-error',
      external: 'i-narr-external',
      eye: 'i-narr-eye',
      eyeOff: 'i-narr-eye-off',
      file: 'i-narr-file',
      folder: 'i-narr-folder',
      folderOpen: 'i-narr-folder-open',
      hash: 'i-narr-hash',
      info: 'i-narr-info',
      light: 'i-narr-light',
      loading: 'i-narr-loading',
      menu: 'i-narr-menu',
      minus: 'i-narr-minus',
      panelClose: 'i-narr-panel-close',
      panelOpen: 'i-narr-panel-open',
      plus: 'i-narr-plus',
      reload: 'i-narr-reload',
      search: 'i-narr-search',
      stop: 'i-narr-stop',
      success: 'i-narr-success',
      system: 'i-narr-system',
      tip: 'i-narr-tip',
      upload: 'i-narr-upload',
      warning: 'i-narr-warning',
    },
  },
})
